### ISSUE TITLE
repo name

### ISSUE THREAD

**Issue by vanzaj** [PyConAPAC/docs#1]
will this repo contain other material than cfp-guideline?

**Comment by darjeeling** [comment]
I don't think so.
can you recommend proper name?

**Comment by vanzaj** [comment]
If it's just for this single doc than the name is fine. If there will be other docs, then maybe something more generic but not as long as useful-conf-org-docs-and-templates.

**Comment by darjeeling** [comment]
how about just `docs` ?

**Comment by vanzaj** [comment]
:+1:

**Comment by darjeeling** [comment]
changed!
