### ISSUE TITLE
Grant push permission to Mark

### ISSUE THREAD

**Issue by yungyuc** [PyConAPAC/docs#10]
I tried to make Lektor work by creating the gh-pages but it doesn't seem that simple.  @darjeeling , do you think it's a good idea to grant @marksteve push permission so that he can work directly in this repo?

**Comment by marksteve** [comment]
Thanks @yungyuc. I'll also update the readme with instructions in using Lektor.

**Comment by marksteve** [comment]
See https://github.com/PyConAPAC/docs/pull/11

**Comment by darjeeling** [comment]
ok added. please get invitation!
