### ISSUE TITLE
Serve static content via gh-pages?

### ISSUE THREAD

**Issue by vanzaj** [PyConAPAC/docs#8]
Would it be useful to serve the content of this repo via gh-pages using tools like http://blog.getpelican.com or http://www.mkdocs.org?

**Comment by yungyuc** [comment]
+1

**Comment by marksteve** [comment]
:+1: https://www.getlektor.com/ is nice too

**Comment by vanzaj** [comment]
Haven't tried lektor. I was under impression that Armin wrote it because he got tired providing "tech support" for his relatives with other static generators...  Mkdocs is dead simple; maybe the best option if we just need to publish a couple of pages. Pelican would be better if we want some blogging-like features.

**Comment by marksteve** [comment]
Found it as simple as mkdocs and as flexible or even more than pelican.

**Comment by yungyuc** [comment]
Anyone would like to make a pull request?  I apologize that it's outside my bandwidth now.

**Comment by marksteve** [comment]
See https://github.com/PyConAPAC/docs/pull/9

**Comment by marksteve** [comment]
http://pyconapac.github.io/docs/

**Comment by darjeeling** [comment]
LGTM! thanks @marksteve
